apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hblNGu0EXo18vA8EfSsQsof3XiL2qIwfX/I1jG5PMA3AeVbM,iv:2kUPp88r5exkd103WhSegBxzdzZH8fDiPi9EEkt3j6E=,tag:HiZw7OzEZ0ogP/y1nEe1gw==,type:str]
    credentials.json: ENC[AES256_GCM,data:nDG0eLMTTI+Bd7IGNIA7OOYlRlMvIQLsCL+kTj5X7Tk6qJvM1+gf5d5I/PE22mCAr413C3thd1nivuEQtAEo14vUXrWATqZOVJQgNF2TYZDHFnKfKCA9txQg+MPeYag2A3tc9pr+pVXwgBy7voLfIOSdCgcYlKkTk5/VyspyXZEdgYr5EW71/0RxNs2FGfR9EofJFQLgmVVl6lVOTgUL81CcH4Gwkd+YeupZnDS9lQ==,iv:a25eyW9eFJNNifwMBfKdDV0z3qCm7PoWmUC4T1ylzNM=,tag:GbMmDYV2B0Gya9gIkp0YBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fuxe2g32ufyqyw4s82fxxymcs47wlt7p3h5qm5kg0t5djnqqza2qjzcl4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMElhZnpvcmFubEpZZkRj
            blJ6UC9ZZ0hrdU16ZWNKeVpwSFhWMFdha0YwCmpNOCsrSzlWeGIyY3Z0cjJISlZt
            ejgyVnNsYW8rM2Y2aW0rZjBaU2Z4R0kKLS0tIFRtSmJuSUJLZmh3S1hBQnRDeCt6
            V0tOcUYzZHVLaG5YRWs0VnhDODJmMFEKD2Y+BsXOi4Y54KzSGqefacgKNQ086yJY
            tq7DzOwSqhc9UF1F5HyeQN8VwlHujCE4xxlxV0DqQ9g655VtI8gJnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T04:31:48Z"
    mac: ENC[AES256_GCM,data:xSHY+Te8w0tgKdxzwfIsUSQMUPE11VGj3PMmaRpW7hkQ3jVsNwEuzq30uUJ9EXSnco+tzrhGBY7DLKXQkhTSHgaRZ8oXs2dCaLv1jscGgPAKDWSQC9zOwkmCOboBD8Pu2ZfbLz+V3x+rwN5/PK2ObblbNKqkU9I8Fm7Z14aNMME=,iv:EFhsKffBH9iXQoM4L3zJWw9AjNxAk2Ag9PreQ+c/Lnk=,tag:XkebzWAViK+jsKjiUl2CBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
