apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0SqnTsxvKeSTB1THAi3vl8QMnuPvSNxX1Lec4hqFR9d5besnDpOY0g==,iv:VlE/LsnLa0HmNGUvyl4ChEofweBBlVA3hsRCU7zywHc=,tag:BNjP2byOTQhfzlhHtF5Mrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fuxe2g32ufyqyw4s82fxxymcs47wlt7p3h5qm5kg0t5djnqqza2qjzcl4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSzNzOWYwbVhYKzdDOFFL
            bDh5NVFiOXhRcDJYcldxdkZ1cFhzcjNUaUU4CllweEFFc2ZPMldXbDhJUlg2OUcv
            VFVMajhmdmZvR2l1T3d4UUpsL2g0bUkKLS0tIElDOG1zWUMxMHF5aGRvT2F0RmxN
            U3pxRHcwQWlSUUxBNFBPUDA5V203RjAKZtm376wE1Qh1gxmzf9ErKEOimSj8Qx5j
            OrnbrI0tRiqw9FKWQGA+g4D2YQdqpyQG4ailpcSC+Co8SW44TKhc9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T22:09:09Z"
    mac: ENC[AES256_GCM,data:AxZ6+yP5fePx+boAOv+Ybqsy6drtAaczjhLe4eZn5YQ63KCUgvfEZba0ilCOxTugPRo5kwoxEXXpwSqIZk624rbXknM+1bHfF20a1+5pUqIu3hMp27DyYoPwaQkY4XpEnPL/BjhcMvCzHvJnhegz5RJBDjBbUh4bu8A66Zqwhg4=,iv:VSsi5zEZjhZ21NEdHTXqp/6AmY9ZgKq2l2dPAlPCZA0=,tag:rFKFowgvlucRiEYMbNbEyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
