---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: false
  tasks:
    - name: Delete /var/lib/rook
      ansible.builtin.file:
        path: /var/lib/rook
        state: absent

    - name: Unlock Disks
      command: 'ls /dev/mapper/ceph-* | xargs -I% -- dmsetup remove %'
      ignore_errors: true

    - name: Remove /dev/ceph-*
      command: 'rm -rf /dev/ceph-*'
      ignore_errors: true

    - name: Remove /dev/mapper/ceph-*
      command: 'rm -rf /dev/mapper/ceph-*'
      ignore_errors: true


- hosts:
    - ceph
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    disk: "/dev/sda"
    disk2: "/dev/disk/by-id/usb-AMicro*"
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: Zap All Instances of "{{ disk }}"
      command: 'sgdisk --zap-all "{{ disk }}"'
      ignore_errors: true

    - name: Zap All Instances of "{{ disk2 }}"
      command: 'sgdisk --zap-all "{{ disk2 }}"'
      ignore_errors: true

    - name: Clean hdds with dd
      command: 'dd if=/dev/zero of="{{ disk }}" bs=1M count=100 oflag=direct,dsync'
      ignore_errors: true

    - name: Remove lxd
      snap:
        name: lxd
        state: absent
      ignore_errors: true

    # - name: Clean disks such as ssd with blkdiscard instead of dd
    #   command: 'blkdiscard "{{ disk }}"'
    #   ignore_errors: true

    - name: Inform the OS of partition table changes
      command: 'partprobe "{{ disk }}"'
      ignore_errors: true

    - name: Reboot
      reboot:
        reboot_timeout: 3600
