apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:gbd9kkJ0zu4PstnafhD/ysMr3Bht2110NTVbPvkbIwE=,iv:TlUBc+DcJ0Zox9ho7sgvnA/opgvt4B7xhuj3aLOEn0w=,tag:4d/j6RYr/9BSFHrcUYHKXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fuxe2g32ufyqyw4s82fxxymcs47wlt7p3h5qm5kg0t5djnqqza2qjzcl4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNHJyVkJzbGV5OGR5YVZH
            RlhJV0RjbHBXc1hiTHNoMFNFTHU0YnVGOENVCjl6M2JRMGJDK1ZXWTlCcEVJbzc4
            UWxicnZWOHcySHBUWkc5NnFGdzZDSTAKLS0tIFdHbU1xc2Z0WUxPbnFlK3B3d2lO
            THJkdFpYV1UvakQzZURqbTREeDE4VHMKKbVFPRJoyXg7AhSL5nzKqLki0046W2t6
            RLWkSA/fdAeCi4w/VfA1e22IQUuAXkYckVB9qEsttnt+61pmjy+h5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T22:09:09Z"
    mac: ENC[AES256_GCM,data:JrwTh3VlW+2Q7Zm578zhAGgq55uJTfFv0cYWiyvQScyZlAUxYlai3l4DegRyi3A7N0dYVnXtXF/u1vuMmdFms6HEOUPpRk0fbkydC6L2GTJpULEPWZamNvxAyVNo4gynuNvYH3h69HfBuKEFI5lHu/BSbC7dPJO1XTe+2uRKMTY=,iv:wPWvnSh1N3eNSRHG5CVqFjTABgW9kJjE2EWFd6tSCaU=,tag:k1082gCzzq2KlM9TQWTjcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
